### ISSUE TITLE
Not full OGG files generation for FSB5 (again)

### ISSUE THREAD

**Issue by lab313ru** [wattostudios/GameExtractor#10]
Here are examples of FSB files that produce not full OGG files: [oggs_fsb.zip](https://github.com/wattostudios/GameExtractor/files/7614683/oggs_fsb.zip)

Good OGG files: [oggs.zip](https://github.com/wattostudios/GameExtractor/files/7614686/oggs.zip)

**Comment by wattostudios** [comment]
Thanks for the further examples. We identified that the OGG page encoder we're using seems to occasionally finalize the OGG stream with 2 pages at once. We knew multiple pages were generated at times, but we weren't sure why. We have implemented support for capturing this extra page and writing it out as well, which seems to have worked for all the examples you provided.

Thanks again for your continual assistance.
