### ISSUE TITLE
Program does not recognize .xtc (Chronicles of Riddick) files as valid archives

### ISSUE THREAD

**Issue by boldc** [wattostudios/GameExtractor#11]
STEPS TO REPRODUCE:
Have Chronicles of Riddick installed (Escape from Butchers Bay/Dark Athena)
Open Watto Game Extractor, navigate to folder where .xtc files are stored (e.g.: .../Riddick/Content/Textures)
Right-click on an .xtc file and select 'Open Archive' or 'Scan Archive'

EXPECTED
Watto Game Extractor displays a list of .dds files in the .xtc archive

RESULT:
Watto Game Extractor displays the error message "No files were found by the scanner"

**Comment by Bizarrus** [comment]
[setExtensions("xwc", "xtc");](https://github.com/wattostudios/GameExtractor/blob/1500c98203c413f211a76d2a27ab02e62f4b8b30/src/org/watto/ge/plugin/archive/Plugin_XWC_MOS.java#L49)

[fm.readString(15).equals("MOS DATAFILE2.0")](https://github.com/wattostudios/GameExtractor/blob/1500c98203c413f211a76d2a27ab02e62f4b8b30/src/org/watto/ge/plugin/archive/Plugin_XWC_MOS.java#L70)

Check if your file has the same content/properties.

**Comment by boldc** [comment]
I am not a programmer, I don't know where/how to use the information you provided to check if the xtc files have the same content/properties. Please provide more detail/context, thanks.

**Comment by wattostudios** [comment]
We are still investigating this issue as time permits. We have tried and have identified that an issue exists, but we haven't resolved it yet. We will let you know when we have a resolution.

**Comment by wattostudios** [comment]
We have finished addressing this issue. Game Extractor should now be able to open the XTC and XWC archives from this game. In the Full Version, you can also display the XTC_TEX images or convert them into other image formats. This functionality is all resolved in v3.14 of Game Extractor - we're not sure when we will release this to the public via our website, so if you want the fixes in advance, please email us at watto@watto.org and we can provide the fix to you.
