### ISSUE TITLE
Excitebots CRC algorithm cracked

### ISSUE THREAD

**Issue by Gamebuster19901** [wattostudios/GameExtractor#12]
I reverse engineered the Excitebots CRC algorithm. Figured you might find it useful, you can do whatever you want with it.

https://github.com/TheGameCommunity/ExciteBot/blob/master/src/main/java/com/gamebuster19901/excite/game/crc/CRCTester.java

**Comment by wattostudios** [comment]
Thanks for letting us know, we have noted it down, not sure what we'll do with it just yet, but definitely appreciate you letting us know about it!
