### ISSUE TITLE
Cannot open .pak archives for 3D Ultra Minigolf Adventures

### ISSUE THREAD

**Issue by WoodingMP** [wattostudios/GameExtractor#13]
Have been unable to open the archives for any .pak files within the steam install of 3D Ultra Minigolf Adventures
- Have tried using the All Files option
- Have tried using the specific 3D Ultra Minigolf Adventures (PAK_TMSAMVOH) plugin
Error: 'The selected plugin was not able to open the archive.'

**Comment by wattostudios** [comment]
We have investigated this format again, and have determined that the extractor is only for unencrypted archives, of which there are some unencrypted archives in particular games, but not in all games. This is by design and we don't have any way to support the encrypted archives at this stage.
