### ISSUE TITLE
Big Mutha Truckers .ar archives not being recognized

### ISSUE THREAD

**Issue by LanceBoyle94** [wattostudios/GameExtractor#14]
Earlier today I found a copy of the Japanese version of the original Big Mutha Truckers, and after finding out it has some new content (a new radio station, namely) I decided to look into trying to extract it, but it's all under a single ARCHIVE.AR file. Googling for info led me to an old forum thread about someone looking to extract a similar file from the sequel, which led me to find out about Game Extractor, so I downloaded it to try it out in case it also worked for the original but unfortunately it is not recognized; opening it I get a "no plugins were able to open the archive" error, and specifically choosing for the Big Mutha Truckers 2 plugin it's not recognized.

I was wondering if that could be looked into, as it's probably similar enough; to note it's the ARCHIVE.AR file on the PS2 version of Big Mutha Truckers 1, specifically the Japanese release (Bakusou Convoy Densetsu) (I've specified the version because it most likely differs from the US/EU versions)

**Comment by wattostudios** [comment]
We'd be happy to investigate this. Would it be possible for you to provide a copy of the archive for us? If so, the best way is to upload it to a file sharing site like Google Drive, Dropbox, or mega.nz and then share the link to us at watto@watto.org . While we can't _guarantee_ to be able to support it, we will definitely investigate it and support anything that we possibly can.

**Comment by wattostudios** [comment]
Thanks for sending the archive to us. We were able to add support for this game (both the USA and Japan versions). This will be included in the next release of Game Extractor (3.14) - if anyone needs it before then, send us an email and we will be happy to provide a development build of GE that contains this plugin in it.
