### ISSUE TITLE
NHL Championship 2000 GOALIES.DAT file not supported

### ISSUE THREAD

**Issue by jlnhlfan** [wattostudios/GameExtractor#16]
[GOALIES.zip](https://github.com/wattostudios/GameExtractor/files/14380615/GOALIES.zip)

Here is a zip folder containing GOALIES.DAT, one of the databases in NHL Championship 2000. I originally tried to open it in the program because other .dat files from the game are supported. But alas, I was greated with the following error message.
![Screenshot_February_22_2024_04_00_08_PM](https://github.com/wattostudios/GameExtractor/assets/31529087/bfaea69b-2773-40c6-b90c-dfd5f78beaeb)

Could you please support this file? If I want to make the mod I plan on making for NHL Championship 2000, this file NEEDS to be supported, or else it will never be finished.

**Comment by wattostudios** [comment]
This issue should now be resolved by the latest update on GitHub. Please contact us via our website if you want a development build for this, otherwise it will be publicly available whenever we do the next release on our website.
