### ISSUE TITLE
doom 3 bfg resourse file convert to png

### ISSUE THREAD

**Issue by y2keeth** [wattostudios/GameExtractor#17]
doom 3 bfg resourse file convert to png not converting back  to rgb correctly  instead of the bimage being YCOCG_DXT5
![pistol#__0100 bimage](https://github.com/wattostudios/GameExtractor/assets/9625773/fc6dbaaa-137e-4b84-af5f-1846cbd628d4)

**Comment by wattostudios** [comment]
We believe this issue should now be resolved. We have added Replace support for Doom 3 BFG "bimage" files, and fixed some other code for DXT5 image alpha values specifically. These fixes will be in the next public release, or contact us if you require them prior to this.
