### ISSUE TITLE
Add ".sdfdata" compatibility

### ISSUE THREAD

**Issue by Aurel-612** [wattostudios/GameExtractor#23]
Hello,

Would it be possible to add compatibility for ".sdfdata" files please? I would like to get voice lines from a Ubisoft game.

Thanks!

**Comment by wattostudios** [comment]
We are always happy to investigate new game files. Could you please email us at watto@watto.org with some further details, like the name of the game and the platform. Thanks.

**Comment by Aurel-612** [comment]
I've emailed you, thank you.

**Comment by wattostudios** [comment]
Thank you, however we didn't receive any email from you, could you please try again, or contact us via the Contact page on our website which might help if there's something blocking your email from getting through. Thanks.

**Comment by Aurel-612** [comment]
Sent it again via contact form.

**Comment by wattostudios** [comment]
Thanks for sending through the files, as well as the other files sdf.sdftoc and sdf.sdfver. As we said in our email to you, unfortunately there seems to be encryption on the archives, which currently prevents us from opening them. We weren't able to figure out the encryption ourselves, and we weren't able to find anyone who can currently handle these archives either (including from other games from the same developer). Unfortunately, for now, we are unable to support this game.
