### ISSUE TITLE
Request: Support for Big Endian RSB from PopCap Games

### ISSUE THREAD

**Issue by LolHacksRule** [wattostudios/GameExtractor#8]
Big Endian RSBs are used in Xbox 360 and PlayStation 3 versions of PopCap's games but are not supported by the tool. Being able to add an endian detector to the 1BSR scripts should allow the formats to be readable. Thanks so much.

**Comment by wattostudios** [comment]
We're always happy to look at other games, to see if we can add support for them.

Regardless of how simple the change may seem, we'd prefer to have some files to look at - are you able to send some to us? The best way is to upload them to a file sharing site like Google Drive, Dropbox, or mega.nz and then share the links to us at watto@watto.org . Would appreciate knowing what games the files came from, and the platform, so we can add them specifically to the supported games list.

While we can't guarantee anything, we will definitely look at any files you send, and will support them if at all possible. If it's just an endian change, hopefully it should be easy to support.

Thanks

**Comment by LolHacksRule** [comment]
I have samples for the Xbox 360 version of Zuma's Revenge and Peggle 2, as well as Bejeweled 3 on Xbox 360 and PlayStation 3. I will be providing an email with links shortly.

**Comment by wattostudios** [comment]
Thanks for sending the files, and your patience. Glad you sent them, as it wasn't just a simple conversion of Endian, there were also some other differences in the archive format which needed additional coding, as well as differences in the PTX image format within the archive. This is all supported now, in version 3.14 of Game Extractor, which will be released publicly at a future date - you can contact us via https://www.watto.org/contact.html if you need this plugin in the interim.
