### ISSUE TITLE
Broken OGG files generation for FSB5

### ISSUE THREAD

**Issue by lab313ru** [wattostudios/GameExtractor#9]
[ghostScream.zip](https://github.com/wattostudios/GameExtractor/files/7605524/ghostScream.zip)
[gearBoy_BootUp.zip](https://github.com/wattostudios/GameExtractor/files/7605527/gearBoy_BootUp.zip)

Correct ones:
[ghostScream_ogg.zip](https://github.com/wattostudios/GameExtractor/files/7605529/ghostScream_ogg.zip)
[gearBoy_BootUp_ogg.zip](https://github.com/wattostudios/GameExtractor/files/7605532/gearBoy_BootUp_ogg.zip)

I've debugged your code, and have found that you don't work with the last data block: https://github.com/wattostudios/GameExtractor/blob/master/src/org/watto/ge/plugin/archive/Plugin_FSB_FSB5.java#L424

`lengths` and `offsets` don't have the last block for every file, also there are some differences after the last block.

**Comment by wattostudios** [comment]
Thanks for picking this up. We tested with the files that you supplied, and think we have resolved the issue. The end offset was calculated incorrectly for FSB archives that only contain 1 file in them, and under those circumstances, if the last data block was less than 128 bytes in size, it would be missed. It looks like the ghostScream.zip file was extracted OK, however the gearBoy_BootUp.zip suffered from this issue. We have pushed a change that fixes this, although it also contains a number of other changes to that plugin for handling MP3 extraction and file decryption - we hope the push contains all the code needed to fix this issue and not break something else as a result of the other changes. The remaining changes are part of the next release (3.14) which isn't publicly available yet, however please reach out to us via the contact page on our website (https://www.watto.org) if you want a development build of 3.14 in the interim.

Thanks again, appreciate you bringing this to our attention
